### ISSUE TITLE
Modrinth errorlog because of config ?

### ISSUE THREAD

**Issue by TimmyWithTheBat21** [ChongYu668/Magic-Moon#4]
well i always get this error here. maybe needs a fix ?

net.fabricmc.loader.impl.launch.knot.KnotClassLoader @675d3402)
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:221) ~[gson-2.10.1.jar:?]
	at com.chongyu.magicmoon.config.CommonConfig.deserialize(CommonConfig.java:44) ~[MagicMoon-mc1.21-fabric-1.0.2.jar:?]
	at com.chongyu.magicmoon.config.Config.load(Config.java:32) ~[MagicMoon-mc1.21-fabric-1.0.2.jar:?]
	at com.chongyu.magicmoon.MagicMoon.onInitialize(MagicMoon.java:15) ~[MagicMoon-mc1.21-fabric-1.0.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) [fabric-loader-0.16.0.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:477) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]

**Comment by ChongYu668** [comment]
e.g. "startDay": 10,
There cannot be any spaces between 10 and colon, 10 is a pure number。
Try this way to see if it can solve the problem。
